"""Package-local backend helpers for the Mandelbrot example.

The Mandelbrot algorithm itself lives in source.nf. This module only exposes a
local helper that creates a shader material for the color attribute generated by
that source. The helper is intentionally scoped to this package and is not part
of the global DSL builtin registry.
"""

from __future__ import annotations

import ast

import bpy

from NodeForge.constants import TYPE_GEOMETRY
from NodeForge.compile_time import reject_compile_time_object
from NodeForge.errors import CompileError
from NodeForge.geometry import _set_material_geometry
from NodeForge.parsing import _literal_string
from NodeForge.statements import _kw_dict, _check_no_extra_keywords

_MATERIAL_NAME = "NodeForge Mandelbrot"


def _principled_base_color_socket(node):
    """Return the Base Color socket from a Principled BSDF node."""
    socket = node.inputs.get("Base Color")
    if socket is None:
        raise CompileError("Could not find Principled BSDF Base Color socket")
    return socket


def _ensure_attribute_color_material(attribute_name: str):
    """Create or update the package material that reads a vector color attribute."""
    material = bpy.data.materials.get(_MATERIAL_NAME)
    if material is None:
        material = bpy.data.materials.new(_MATERIAL_NAME)
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links

    bsdf = next((n for n in nodes if n.bl_idname == "ShaderNodeBsdfPrincipled"), None)
    if bsdf is None:
        bsdf = nodes.new("ShaderNodeBsdfPrincipled")
        bsdf.location = (260, 0)

    label = "NodeForge Mandelbrot Attribute Color"
    attr = next((n for n in nodes if getattr(n, "label", "") == label), None)
    if attr is None:
        try:
            attr = nodes.new("ShaderNodeVertexColor")
        except Exception:
            attr = nodes.new("ShaderNodeAttribute")
        attr.label = label
        attr.location = (-300, 80)
    if attr.bl_idname == "ShaderNodeVertexColor":
        attr.layer_name = attribute_name
    else:
        attr.attribute_name = attribute_name

    target = _principled_base_color_socket(bsdf)
    for link in list(links):
        if link.to_socket == target:
            links.remove(link)
    color_output = attr.outputs.get("Color")
    output = color_output or attr.outputs[0]
    links.new(output, target)
    try:
        material.diffuse_color = (0.1, 0.25, 0.9, 1.0)
    except Exception:
        pass
    return material


def compile_apply_mandelbrot_material(comp, expr: ast.Call, depth=0):
    """Compile apply_mandelbrot_material(geometry, attribute_name)."""
    kws = _kw_dict(expr)
    _check_no_extra_keywords(kws, set())
    if len(expr.args) != 2:
        raise CompileError('apply_mandelbrot_material(geometry, "attribute_name") expects Geometry and a string')
    geo = comp.compile(expr.args[0])
    reject_compile_time_object(geo, "package-local backend helper argument")
    if geo.typ != TYPE_GEOMETRY:
        raise CompileError("apply_mandelbrot_material() first argument must be Geometry")
    attribute_name = _literal_string(expr.args[1], "apply_mandelbrot_material() attribute name", comp.consts)
    _ensure_attribute_color_material(attribute_name)
    return _set_material_geometry(comp.group, geo, _MATERIAL_NAME, depth * 240, -depth * 90)


BACKEND_BUILTINS = {
    "apply_mandelbrot_material": compile_apply_mandelbrot_material,
}
